"""empty message

Revision ID: bac817d9b30d
Revises: 5e501c22fb2b
Create Date: 2025-09-04 13:11:16.094214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bac817d9b30d"
down_revision: Union[str, None] = "5e501c22fb2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "done", "error", name="unit_image_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unit_images_unit_id"), "unit_images", ["unit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unit_images_unit_id"), table_name="unit_images")
    op.drop_table("unit_images")
    # ### end Alembic commands ###
