"""empty message

Revision ID: 7fc73c5241ae
Revises:
Create Date: 2025-08-22 20:52:37.924856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fc73c5241ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "company_role",
            sa.Enum("owner", "member", name="company_role_enum"),
            server_default="member",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title",
            sa.Enum(
                "sales",
                "addStock",
                "salesReturn",
                "writeOff",
                "newPrice",
                "stockReturn",
                name="action_enum",
            ),
            nullable=False,
        ),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_id"), "actions", ["id"], unique=False)
    op.create_index(op.f("ix_actions_store_id"), "actions", ["store_id"], unique=False)
    op.create_index(op.f("ix_actions_title"), "actions", ["title"], unique=False)
    op.create_table(
        "role_user_in_store",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "seller", name="role_user_in_store_enum"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_user_in_store_id"), "role_user_in_store", ["id"], unique=False)
    op.create_index(
        op.f("ix_role_user_in_store_store_id"),
        "role_user_in_store",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_user_in_store_user_id"),
        "role_user_in_store",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(op.f("ix_sessions_refresh_token"), "sessions", ["refresh_token"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column(
            "measurement",
            sa.Enum("pieces", "meters", name="unit_of_measurement_enum"),
            server_default="pieces",
            nullable=False,
        ),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("average_cost_price", sa.Float(), nullable=False),
        sa.Column("retail_price", sa.Float(), nullable=False),
        sa.Column("keys_image", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(op.f("ix_units_store_id"), "units", ["store_id"], unique=False)
    op.create_index(op.f("ix_units_title"), "units", ["title"], unique=False)
    op.create_table(
        "actions_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity_delta", sa.Float(), nullable=True),
        sa.Column("cost_price", sa.Float(), nullable=True),
        sa.Column("retail_price", sa.Float(), nullable=True),
        sa.Column("previous_retail_price", sa.Float(), nullable=True),
        sa.Column("discount_price", sa.Float(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "sales",
                "addStock",
                "salesReturn",
                "writeOff",
                "newPrice",
                "stockReturn",
                name="action_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_actions_transactions_action"),
        "actions_transactions",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_actions_transactions_action_id"),
        "actions_transactions",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_actions_transactions_id"), "actions_transactions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_actions_transactions_store_id"),
        "actions_transactions",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_actions_transactions_unit_id"),
        "actions_transactions",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_actions_transactions_user_id"),
        "actions_transactions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_actions_transactions_user_id"), table_name="actions_transactions")
    op.drop_index(op.f("ix_actions_transactions_unit_id"), table_name="actions_transactions")
    op.drop_index(op.f("ix_actions_transactions_store_id"), table_name="actions_transactions")
    op.drop_index(op.f("ix_actions_transactions_id"), table_name="actions_transactions")
    op.drop_index(op.f("ix_actions_transactions_action_id"), table_name="actions_transactions")
    op.drop_index(op.f("ix_actions_transactions_action"), table_name="actions_transactions")
    op.drop_table("actions_transactions")
    op.drop_index(op.f("ix_units_title"), table_name="units")
    op.drop_index(op.f("ix_units_store_id"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_role_user_in_store_user_id"), table_name="role_user_in_store")
    op.drop_index(op.f("ix_role_user_in_store_store_id"), table_name="role_user_in_store")
    op.drop_index(op.f("ix_role_user_in_store_id"), table_name="role_user_in_store")
    op.drop_table("role_user_in_store")
    op.drop_index(op.f("ix_actions_title"), table_name="actions")
    op.drop_index(op.f("ix_actions_store_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("stores")
    # ### end Alembic commands ###
