"""empty message

Revision ID: dafe1017e250
Revises: bac817d9b30d
Create Date: 2025-09-10 12:10:17.097246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dafe1017e250"
down_revision: Union[str, None] = "bac817d9b30d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unit_images", sa.Column("key_100", sa.String(length=255), nullable=False))
    op.add_column("unit_images", sa.Column("key_300", sa.String(length=255), nullable=False))
    op.add_column("unit_images", sa.Column("key_1280", sa.String(length=255), nullable=False))
    op.drop_column("unit_images", "key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "unit_images",
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("unit_images", "key_1280")
    op.drop_column("unit_images", "key_300")
    op.drop_column("unit_images", "key_100")
    # ### end Alembic commands ###
