"""empty message

Revision ID: 8fc070dc489b
Revises: 355ef5c74914
Create Date: 2025-09-26 13:06:15.672745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fc070dc489b"
down_revision: Union[str, None] = "355ef5c74914"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("unit_images", "key_100", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("unit_images", "key_300", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("unit_images", "key_1280", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("unit_images", "key_1280", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("unit_images", "key_300", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("unit_images", "key_100", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
