from typing import Any

class CustomRedis:
    def __init__(
        self, host: str = "localhost", port: int = 6379, db: int = 0, decode_responses: bool = False
    ) -> None: ...

    # --- Строковые операции ---
    async def set(
        self,
        name: str,
        value: Any,
        ex: int | None = None,
        px: int | None = None,
        nx: bool | None = None,
        xx: bool | None = None,
    ) -> bool: ...
    async def get(self, name: str) -> str | None: ...
    async def ttl(self, name: str) -> int: ...
    async def rename(self, src: str, dst: str) -> bool: ...
    async def exists(self, name: str) -> int: ...
    async def expire(self, name: str, time: int) -> bool: ...

    # --- Списки ---
    async def lrange(self, name: str, start: int, end: int) -> list[str]: ...
    async def lpush(self, name: str, *values: Any) -> int: ...
    async def rpush(self, name: str, *values: Any) -> int: ...

    # --- Общие операции ---
    async def delete(self, *names: str) -> int: ...
    async def aclose(self) -> None: ...
    async def flushdb(self, asynchronous: bool = False, **kwargs: Any) -> None:
        """
        Delete all keys in the current database.

        ``asynchronous`` indicates whether the operation is
        executed asynchronously by the server."""

    # --- Pipeline / транзакции ---
    def pipeline(
        self, transaction: bool = True, shard_hint: str | None = None
    ) -> "CustomPipeline": ...

class CustomPipeline:
    async def execute(self) -> list[Any]: ...
    def set(self, name: str, value: Any, ex: int | None = None) -> "CustomPipeline": ...
    def rename(self, src: str, dst: str) -> "CustomPipeline": ...
    def get(self, name: str) -> "CustomPipeline": ...
    def lrange(self, name: str, start: int, end: int) -> "CustomPipeline": ...
    def delete(self, *names: str) -> "CustomPipeline": ...
